sudo: required
services: 
  - docker

before_install:
  - docker build -t dimpl05081992/docker-react -f Dockerfile.dev .

scripts:
  - docker run dimple05081992/docker-react npm run test -- --coverage