sudo: required
services: 
  - docker

before_install:
  - docker build -t dimpl05081990/projectreact -f Dockerfile.dev .

scripts:
  - docker run dimple05081992/projectreact npm run test -- --coverage