sudo: required
services: 
  - docker

before_install:
  - docker build -t dimpl05081990/projectreact -f Dockerfile.dev .

scripts:
  #- docker run dimple05081992/docker-react npm run test -- --coverage
  #- docker run -e CI=true dimple05081992/projectreact npm run test
  - docker run dimple05081992/projectreact npm run test -- --coverage